http:
  port: 8081

admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  restaurant-search-api: 
    host: localhost
    paths: '/'
  order-search-api:
    host: localhost
    paths: '*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org' 
  restaureant-search:
    url: 'http://localhost:4000'
  order-search:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  restaureant-search-pipeline:
    apiEndpoints:
      - restaurant-search-api
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: restaureant-search
              changeOrigin: true
  ordermanagement-search-pipeline:
    apiEndpoints:
      - order-search-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: order-search
              changeOrigin: true